---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: overseerr-appdata-nfs
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: overseerr-nfs
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: /mnt/tank/db
    server: 192.168.86.44


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: overseerr-db
  resources:
    requests:
      storage: 10G
