apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:DF7HuFxAVGMBLoIJ5fk3CNs7qRx8ee0J79I1UiMv9iskttyJ,iv:D9FbkMNmm1PmpKe+8H47UQXMLge4J4R2iBvBqi60kfk=,tag:WENOALhR8f/45P+ZiBeiAg==,type:str]
    credentials.json: ENC[AES256_GCM,data:+f+VyTcCqr7mkaF9+inmGD2stEe1cD1nL2/dW6bFUG4y2zPqeXsVY/dMDJ72RF9hCNiecTtvAbIgwi4+pAiWkqZ3DG6+cGQwICVl5+Kb6n9G99c376M0GCUHlRWNb+4bZp2kIG6+Edi+T1CP5shQJ2qb2NL4LAk5Ww9JxxhuxeN0cTu0q2FaSZgbqpqcyPT1+4naFhFMiP9BmRTwxQ+oSzUNdNqJL6gNsQXxXJK/yA==,iv:DjjrHLOh6rDvIhMUwTF1jbXyfoeFSmNrEw6hKDYpkfM=,tag:38GY1Bcgx4KE8hehJa6/kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcFlRWkhhZ1NCekw3M0tB
            TlcyRHdUSkVrMkpMa0pid2t4VjAwTTI1WVFnCk15RFVxcmxuS1JaY1MrSHlWalVz
            WUFXeWppTHFsdjBaMjFhVUR2NnY5WFkKLS0tIGtFNW1sR2srM004UmtveXZsNXBm
            TW1HUis1YktGK2RNNCszSmRvY1BoUnMKONmd95riMXW56iOFtzfoFLuGpDru3uAr
            IAPNc0h2Ckyneds07QKdZBp+KGGchhMY92q+o/ViEDc8OYanrt7E1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T03:46:06Z"
    mac: ENC[AES256_GCM,data:3DdHcmQ+YxPm8+xwh84VinIBQ46vGBL2Yi7aBF+BosHaBXimR3bdlM5FiRRuJ81ELZTAUVTFKs6AfQjeoUOFqhHnw5CvceYR8ZsmQWPILhrTCuNt6EZrgBWFk55a8t/DtS+wlOgKFesVXCJocKGAdE71y257fedp/T63bD+Vdyg=,iv:x6/9Z4Qg/MjsRsFELo7uuJd4ZhDYB93XzFTrppu0iSI=,tag:OGEU6Xz9Glb4AQcnYsB33g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
