apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:YoYj3Yd1/PSM3F+eOPqGGtASbJ0eTc6SEoIK7ZPHUT5TNdfb+vnMrg==,iv:Tls2MxQtzPtzeph1oFhyR4uR06Ehx0f/M+27jrv/ZxU=,tag:ciYRV2oceW0PvU5Gfj0YrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN3JBRGNxVzRmeTJraDBw
            K1pZaExQTnJUSU9SMWJDWHVtWkVhQTFLdjJJClA4TnUzdXdVVWZCN1NESG82YUk1
            UHozMkhiWmVqR3Q3T3o4eTF3ZXFiUFkKLS0tIFFTcUVFN2FDcGVFUWJjbEcwWXNQ
            MWd1M3U3WFpBSHprdHBic0lLLzZmek0KOmTHo3poG+/tYpI9KV1FTifNM2sSIOmn
            bgPANv5re8bju+jxtIIRi88KdumW3Kaudp3GGcXbhf6lQTdPYrSYLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T18:18:40Z"
    mac: ENC[AES256_GCM,data:GNmH7t04/Q8tGyd7Wq9cKfW2In9u7eT1DD4iTkrj0Bw0rP46IQ2lehII+D5ZEzBl3cqiaT0+/uFSv3j+U+k5uL6igks4bRa9sGcoRWJaVMVUQWkbz+gho/r/QtT1ML0a0hXXfNr26dB7LkkimMhLC6gc+Xd6vsY7sZDucAV2OzM=,iv:rBxw09Rxo6npR4m8WGu38OE+N9BfhbRFWA6rXXjXFgw=,tag:08naM1qk/H/62A0SXp/QlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
