apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:pKMXBQgc6Es+1aNQB9ucohcfVQEUcqncHhVbosCh1/hcM/ul7Kw3xw==,iv:GecoIisH1uwBLnJI/dqFD4hhOaRPbLV10qARPTRABYA=,tag:dwNQYZtYbMjkJWiuOwl1+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVnVDUHllRHBiQkV4T1Bu
            QUVHT0NIVVpnR3VIQ2YwVHl2aE1FQkx2RmljCmRFbElyVkgraWNoNUJHa09ydXBa
            TjREWUc5WDFEWTd1ZzNySVkxRDZFV2MKLS0tIFJqOERscU9Rc2VBNzJpajQ4KytR
            NWtVL3UvMWFyWjJmZDF2c0ZmNEMyak0KKWPUPBpgsGeR3Q/9hyTxGg1j1OTU73er
            usAOEbaSZuSSODoc3JnE9BMaNw2wur631XVNaHzxkCammcg+0DyLPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T03:53:20Z"
    mac: ENC[AES256_GCM,data:1cuLKP4jOkDLS3Ic0u7LgFJzSykkrGzaZ7LZ2SPBZWiqSzO254t/iQXSsCkAcZs0Q/SnwwWVQCKTR7BRg2BKNTWU9dttlY+hMHFvnnYZq2L0YDglxSCHrMfgLYCgEVh/Jff6kMQyrdrSkfnSsrjiyNjPpUbJ6lW/jKyNJBBRMFQ=,iv:VkH3VmQj+2jm9pelf7ziIexShRhzilSQ+EYUNS9PFT4=,tag:niDKhWhwX9KE2dJTCzyhYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
