---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scrypted-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: scrypted-nfs
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
  nfs:
    path: /mnt/tank/db/scrypted
    server: 192.168.86.44

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: scrypted-nfs
  resources:
    requests:
      storage: 100Gi
