apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:58GXdmq00SDblaQ4QIqbFOJVWQ+TXaUp4auVAWF+Xi7pLhYKIgE0/2InvQHlogB/2+ypzAe2V1cByBUmZggEyR/xbwMwVbS7J9e+RhSqmlS8T/JDdmac3+qo94uwNQ==,iv:nRQ9OGmXaRbI4nWQPXOp6AfQeaEfQvIaaQsOREDV8Bs=,tag:1Vyn5M5KjwTcTaRoEnBYdQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wssgfhguHWn4ab0WHDSk,iv:rEh+u3zxkteAsw9NHaf4I/xegBlvLrbR2yfnGZmPHtg=,tag:HyHtT1598bRt+BkU9rE2bg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:UYs+MC7A0LwGy8xck3ZPI2mNu20sbw==,iv:XhIjj5i2rnU/FNUyYxs+SjddvgamPTTi+kcdVWO4LpU=,tag:kAQZrJjusrUr8vipyuSVbw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KU8VAY/UFPPsxnDFKplWiJ3H/drFfDVFM5FWI44e2kaRdDf6,iv:lP/9o4XFark2sl9HfYbQkmbDq+fr3sshSmH764/k+q4=,tag:/m9TnX5rBYbg2gU99XE5JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbDNPeDRRZGZ1WGF0WXha
            b0FVNXQwMFM3V2hSZEhRNCtMSEd0b2JCR1NjCmJpTktmMitkWno4YUpYQlBlZ1dy
            N2tETlRFb21IeG5ERlBybFpURmpySE0KLS0tIGkwUUFwSEdvMDhESzM2UkNCeGQx
            RGRnaWxCVm4xQ2MraWVGSktldjZ6QmcK+GWdO2kboKIlj1zZOzY2JAzhQXWfg31z
            2+M1SNj8QQTAgzMaa4otmh85GJtVIJN7pd1uJhM+2htYlDg56Z8Faw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T18:18:40Z"
    mac: ENC[AES256_GCM,data:enh8Rju5EKzrIq/vNvxak5nKfRwM5xYe8p4lSpwGaVBmIIc1JaorFcglx92R6nuAfZ59OLaDB3/9UTdrrvjCkd3whlzH6wTYu1EFVTMZyH6LfjtrtL9mCOI0ttxpaB9ZTDR79LJ2OMSTcElhJe+CcqpntUuKAuYvxm8Ka/5OQXU=,iv:3L2Ge925I5skSb/x//L2K7KnPXtA84Zn9Nlj7ZD/1Eg=,tag:PwX1xkjaYJeI51MSFa92SA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
