apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pat-secret
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:356iXczyBNU4/HXP6sn3IYB7FbHnPWcjiGJreP5fxGyyxrAbSTef+q/Yx+bpr4U7v66v/iCSdYhbcYb+pZXXKOgLKTFGqD71dCQXjGjzL+NL6LekPanyO4OxYQb3xDP62Cy1MMOzBGcUrCZ9fd2d+g/JpgouXl578OTpnkeMhCECBI+ADLOsPNnorts=,iv:ckNgprQdNWk5X4jDpuVp+Ys3N19Ke5PndsADE8ux438=,tag:R7CSIfFIc5tUAbCN+DVRuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WkpqRDMrWFlqenV0LzJ4
            MXZxUndxR25CMUNvUEk1OWZCZHMwVEhVZERFCkw3MzBDcmhwSC9xajJhYlRIQlc4
            OUh2clR1akNJQkN0MXV3MUpKVDQ2ZWcKLS0tIGJjYTRwcVNReEdnQTRzd2pjT2J6
            cGdCK09EbStERUJ4UGVISEhHb0ZSWHMK/iDej+58Y5abjZ1z0Hk1bz2IFN1Y6zr5
            zgenAzBBJ2NgemiZ1VFrlvDQecwTW1T2m6k/Fxn+v7jAbmt1Acu99w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T00:38:21Z"
    mac: ENC[AES256_GCM,data:RE/z7a16esyjulMph19cfFhSUNB0FtiHgnVPuARij8pqWLEOXKHp46rSS4AxMlSX/CUuTk9jOeyn3pinQjs9cl/6hJ7Jvzc3+wb7tH80jZpHRFAbYM+gwRzg974hMqrp4bFl3rwaDYfT7WTA79onQfcyuKzb/rh/I+rLM5KG92k=,iv:a9KxEZE8bkd+NV89te/h41NAa5Y1Z2F9Wz/948zKp5Y=,tag:g5sM/LJhAR+hmvgqr9p/OQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
