apiVersion: v1
kind: Secret
metadata:
    name: dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:AL4GWK/TootQW72AHjXTeLKW7eyyXFn/ntTGYrX6K4pdRWYObrmXuFK9idnqyWefFxuBc1ca6ixHZheT9hJYRafiflEeOE3Y9+KRpupPHrIqMnw8flSm3BcJMpKyLTTZv8EgJ2P4Qd0w08ApvHn234pDB9tsUKCwcNwGwcAJoJ720v9LlP6b5vivNPU=,iv:OVLQrdoy16pg4zcxMAqROdl/0EaJL/oBHpXYquEOchM=,tag:fpjfCrQUIUVx+wcyiDxA7Q==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWXdGUzJlVTh1bUxxRTdl
            ODRGTXB5VmFwWGFhWURxUXNkWkpIWG4zWVhzCjQzb203Uys0M1lMTmswRXZaV0Yx
            dHNMYUdkWWFOaWZHbndhSGFuYTUyb0EKLS0tIEpaa3dML3pFdDFIblRQTU1BSVBz
            UXZ1WE95QWdjR3F4V1oxdzB5bVRzM1UK15d+c+tjq69UinM9V8TiSVJF+ann/THs
            EVNbuGfhfNETnIOdf8veOPAV8JFrRWwjz7C/439yGFu5ZbAzBrIUtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T00:54:29Z"
    mac: ENC[AES256_GCM,data:oPNEo43mfebZZV3hqBrU2yGG8wWRFbhUCUeDf536F1uEDdqa2PxV+c/qbROL1LqFvvDt0noRwMz1TXc4ey91DBn3td1zm4PTMlh8sYzNj/N0rL8QRBdgzpA83+i0c+OeCZEzSrvUgtX1ly9hYVNueFpF4ExtnfEsRpEhKImSoss=,iv:EOx9DXxX4jmJ4hB4No4YrHxu73L9rA5mCXlvnB3BdyI=,tag:ni6bVsoNJpGVjAt6kL/J8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
