apiVersion: v1
kind: Secret
metadata:
    name: stacks-secrets
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:rqhbcFAAzhqIXU8OtjyNlhViag2qgGRJjxiA+lYWOpdxVz2157YMVZlxyGrXmvBcQSJfScaTht6690nQ6YckG01B2O/RaFR/K+l0pHRWdQNjHF7VG5ndA/9CISfE9RyzZzPZVIfAkH9W3AB3wAbF8/7nux7ouDlRXW11x5Xay4G051baXcgk0o8abOOXrl08,iv:4+XI6YMHqdOFbA7nbwO1XC+g6phlVYhuinTwN/Wg76Q=,tag:t0WVCoIDeadNmJ8X9FhLlw==,type:str]
    MYSQL_DB_HOST: ENC[AES256_GCM,data:SYjzTVKfIiir2CSdv9YbbQ2BcoICSA==,iv:B5RUndiduW4tWp2C0cH322l1UaLZgO1zJhnn7SHcCX0=,tag:BU3mcar+pXSci4EDJb7kBQ==,type:str]
    MYSQL_DB_USER: ENC[AES256_GCM,data:BcBCYAkMnq9jMGlYEPzu56tEZ6k=,iv:pgw+dKqKhVqjWV5QL0YhEoIzcHIHXVQ7vWSElJmMSy8=,tag:Ivyikg8jslgGQq6/Imdh0w==,type:str]
    MYSQL_DB_PASSWORD: ENC[AES256_GCM,data:4unWd5z04mcJ2FaE7zjdk43+wQOXZh/nT1hBcwj7WXSMob/kQkLAJtPYYsr6JO9BzcM3pro=,iv:5ypnsk/8rfFcfikujkug8/noT15p66BUTo52WNgYLog=,tag:STZxEmk6m3dsnjkbu2GuIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVFFLU0tjdEtpZHBqMlM0
            VVNMTmdhRCtjbVNmNG9vazFPZFZBVGVKQkNVCk5xc3VzR04ya0hLVlJNMnB3K2lq
            TC9zU0x0cTBjdkhPUkJRUklmaDNGQmcKLS0tIDl3VVdNbnJDcUZiWDJ4am45TnNW
            MXlZdHo4ajZsZm5Nc2ZsVm5GRU85MlEKWdcn/jbqJhBwOuKP1OVloWhY8vJfc6sH
            sOAJaMe9OjuZVIpCJx5VsHAkbMdVjtenw4EOss9hNE4LfNBSZITzng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T00:54:55Z"
    mac: ENC[AES256_GCM,data:vYDEKr/e888nGWGDO8TblN7LGTgMDRRx3PoifBvvjPUJzoPjiZ0v+zvvO8aQC15g4TFTDsrUMNBTfqBfCfr9nooR/bz1w8ojMCNIifnFSWf/MjmlnAjrn06WuuGUAYVIVMsUc+nd/rxzupC/lB7cAh2EfyoWPDqyTXu33NNFM0g=,iv:8/yP71Hw4FRe4rPDieMLFsx4bjFoLW71xR31CpWKiLs=,tag:1OFezD0x8Pwya1IOl4PQvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
