apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:iIaK76Me2l8I5UCXCXRXS0qlpPvsWHZw,iv:EtwqQovPxEte7hnv+f2IpEuPWUwLHgJ/b3JQm7Dmtkg=,tag:I/Z50qyaAdqA0K/0vs5Sag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMXp4Ty9xVEM1QmhqVVkx
            VjZCQWNuNDhEU0pENkxnRlF2NnRXQUd5dkVBCk03TlVPZ21pY2ZhdjAyK3FPcUVQ
            Q2txVFZBV0M0TnRycVg5bmhpK3ZrQVkKLS0tIDlEQ1ZpOEJ2bmlUdFhMS2REN042
            NnZaN2hSeG9vQ2dFQld3b3c5K3VXNVUKJf50nI5dWgskSX3ALoQq7GBEKDpTdF3y
            9OthFMBYFVTBhJZft5AB4Zk1vmviQ6Cv6XCJyk4kBICpDmtHTArPiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T03:53:20Z"
    mac: ENC[AES256_GCM,data:/oRNRJ//VtIegHVApxLlADfyzP8X9WI7QdmVehc/Wd/iB35F1NeYZXze7+J6/nf4dsm5Sidxc7dF4piDNTxKE5tvxYLW4Vy215ckjJxWNsuj5ugRSpl2AWjXX5C4ziiDFubX3qrqmkoTt3U9fd46x6ZjdIle+tmAr41qjwVsp3w=,iv:m1aZoZOe8g2CKRRtzt1mmwm+BS5WfD4MaTj890iiX68=,tag:42hvzabniRE/cDbPH6hCVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
