apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:pE0e9E5qTGxLHsAjmIQ42OLCWjd4Is5d/iLU787Sr6Q=,iv:DfkdE6ctVI9u3gD4rxkjJuS0OWHMbL8ZuZQCWByMwio=,tag:ulBNEbzodjwGcNEA/8JhRA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:8aCakJPSBzIdXhAEtmBgcqAgJnpI3UZiXpDVDZTVLXSEzof3,iv:+uJmBLsODbfnIWDqKQNfciVr8E1nTdzqLiGEd4w5kSA=,tag:bcuDlu19fu3yU5cYsMNIwg==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:3imjwtANGU2WJLHjp8N/GSbkqmO5KUfw5Tx3eqwxD5k/Nu3VTVOMNQ==,iv:7B8MRaQHtdqaIh3ZECqzuwdH+8Zdf/BeOJseFadpj7c=,tag:kp7IofcgVW+h5MjLjbd9gg==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:B+Kp8A==,iv:es0bZqRldbzzuMGmOmrcg6wA1Wjb5ZC4yfXrYIDFJfk=,tag:Lgv/nJRaYJCuhPu/1wsSqw==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURFhWKzBENXZxczNxekZO
            MGIyTzlURHo5V01Gd1ZvbVNJUDFvRVpiWkhnCjg1dm9aSFU2TXAzTEU3N1Vhc2lD
            RmxwaFZaeU44enZ1Mi92QUVWenAxeVkKLS0tIFAxcER3OUFKb3htS1hZTWZKS3Zl
            ajlWT05sNU1GdlcxUjVQQ1JYcHR3UFEKeTK5ScGnZK+laRrVIiFbj7/sshWayY1E
            ANN6hl7qTkQ2McarNhsDRGxxVLGpUepcEkC8kMQ1m4TZXxQy4u39GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T15:24:46Z"
    mac: ENC[AES256_GCM,data:AVT/VcPxZ8IoswDN1SvrUUNX26QYDCtnMDe+UfTKw1hnhOrAd9GAtNxMaaMlKIkOQTlqPJJS2MbSnaIWJ+uruX+5zvf/gFm5YErtw1yJRluXBTZC6MOQPVjT5FPBEtjqIsggCMza2h8RaX0VFl6ZAK7w7a7X4BanlzsyOwGQTjE=,iv:d/Wtd8yiDo+oDCPTvoI+47MKScKG/hoiB1F1xhWEeVM=,tag:PR/kdWvcYMQDTOyk/FqkAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
